export const POSTS = [
	{
		_id: "1",
		text: "taj mahal copy😍",
		img: "taj.jpg",
		user: {
			userName: "d2",
			profileImg: "dp2.jpg",
			fullName: "Dhiman",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					userName: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			userName: "johndoe",
			profileImg: "dp1.jpg",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					userName: "janedoe",
					profileImg: "/avatars/girl2.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "banner(1).jpg",
		user: {
			userName: "johndoe",
			profileImg: "/avatars/boy3.png",
			fullName: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "banner(2).jpg",
		user: {
			userName: "johndoe",
			profileImg: "dp2.jpg",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					userName: "janedoe",
					profileImg: "dp2.jpg",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "DD",
		userName: "gg",
		profileImg: "dp1.jpg",
	},
	{
		_id: "2",
		fullName: "kk",
		userName: "ii",
		profileImg: "dp1.jpg",
	},
	{
		_id: "3",
		fullName: "mm",
		userName: "aa",
		profileImg: "dp1.jpg",
	},
	{
		_id: "4",
		fullName: "oo",
		userName: "tt",
		profileImg: "dp2.jpg",
	},
];